# Dockerfile para el frontend con Nginx
FROM nginx:alpine

# Copiar archivos estáticos del frontend
COPY ./UTMentor /usr/share/nginx/html

# Copiar configuración de Nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Exponer puerto 80
EXPOSE 80

# Comando de arranque
CMD ["nginx", "-g", "daemon off;"]
